### ISSUE TITLE
A bug in Count function

### ISSUE THREAD

**Issue by panktigosar** [wyang17/SQuIRE#104]
Singularity> squire Count -m /output_files/alignment_intron -o /output_files/repeats -n _Aligned.sortedByCoord.out.bam -b hg38 -g 112 -r 150 -v
start time is:2024-10-08 10:32:12.302360

Count.pyc

Script Arguments
=================
count_folder=/output_files/repeats
EM=auto
clean_folder=squire_clean
fetch_folder=squire_fetch
name=_Aligned.sortedByCoord.out.bam
tempfolder=False
verbosity=True
pthreads=1
strandedness=0
read_length=150
build=hg38
func=<function main at 0x146cf9b8fc80>
map_folder=/output_files/alignment_intron

Traceback (most recent call last):
  File "/usr/local/bin/squire", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/usr/local/lib/python2.7/site-packages/squire/Count.py", line 1560, in main
    paired_end = is_paired(bamfile,basename,tempfolder,debug)
  File "/usr/local/lib/python2.7/site-packages/squire/Count.py", line 325, in is_paired
    return paired
UnboundLocalError: local variable 'paired' referenced before assignment 

The bam files have come from paired reads and were confirmed with flagstat.

**Comment by koepfla** [comment]
So it wasn't for the same variable but I had a similar error when I was running this pipeline on Tru-Seq reads:
```
File ".../SQuIRE/squire/Count.py", line 378, in reduce_reads
    prev.line_split[15]  = prev_TE_ID
UnboundLocalError: local variable 'prev_TE_ID' referenced before assignment
```
I fixed it by wrapping the code chunk for that section in an if/if not statement.


So the original code (lines 378-382 for my error specifically):
```
			prev.line_split[15]  = prev_TE_ID
			prev.line = "\t".join(prev.line_split)
			outfile.writelines(prev.line + "\n")
	if not debug:
		os.unlink(read_file)
```
The new code chunk for that section (new lines 378-383):
```
			if prev:
				prev.line_split[15]  = prev_TE_ID
				prev.line = "\t".join(prev.line_split)
				outfile.writelines(prev.line + "\n")
	if not debug:
		os.unlink(read_file)
```

That resolved the issue for me, it may help anyone else who is encountering a "unbound variable" error.
