### ISSUE TITLE
Error in Count - filter_abund()

### ISSUE THREAD

**Issue by cpacyna** [wyang17/SQuIRE#15]
Traceback (most recent call last):
  File "/users/cpacyna/miniconda3/envs/squire_git/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/users/cpacyna/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/users/cpacyna/SQuIRE/squire/Count.py", line 1564, in main
    filter_abund(abund_ref,genename_dict,False, read_length)
TypeError: filter_abund() takes exactly 3 arguments (4 given)

**Comment by cpacyna** [comment]
Thanks, looks like that error is fixed!
Now I'm getting this:

Traceback (most recent call last):
  File "/users/cpacyna/miniconda3/envs/squire_git/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/users/cpacyna/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/users/cpacyna/SQuIRE/squire/Count.py", line 1568, in main
    os.unlink(outgtf_ref_temp)
OSError: [Errno 2] No such file or directory: '/dcl01/leased/cpacyna/TCGA/scripts/colon/colon_new/squire_count_2018_07_11/TCGA-A6-6780-01A-11R-1839-07_COAD_t_48_high_outgtf_ref.tmpZnFYKB'

That temp file doesn't exist, but there are tempfiles being made in the squire_count folder.
