### ISSUE TITLE
Error in Count - prev_TE_ID not defined

### ISSUE THREAD

**Issue by cpacyna** [wyang17/SQuIRE#18]
Half of my count jobs are going through, half stop with this error:
I've come across this error before but it did not affect so many files as now.
Thanks!

Traceback (most recent call last):
  File "/users/cpacyna/miniconda3/envs/squire_git/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/users/cpacyna/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/users/cpacyna/SQuIRE/squire/Count.py", line 1683, in main
    reduce_reads(paired_bed_tempfile1_sorted, paired_reduced_tempfile1,debug)
  File "/users/cpacyna/SQuIRE/squire/Count.py", line 378, in reduce_reads
    prev.line_split[15]  = prev_TE_ID
UnboundLocalError: local variable 'prev_TE_ID' referenced before assignment

**Comment by nrius** [comment]
Hi!
I think I have encountered the same error, but for me it happens for every job. How did you solve it?

The end of Count output looks like this:

```
Creating unique and multiple alignment bedfiles 2020-02-12 10:42:13.942414

Intersecting bam file with TE bedfile 2020-02-12 10:42:13.942440

Combining adjacent TEs with same read alignment 2020-02-12 10:42:24.015916

Traceback (most recent call last):
  File "/home2/nrius/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home2/nrius/miniconda3/bin/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home2/nrius/miniconda3/bin/SQuIRE/squire/Count.py", line 1607, in main
    reduce_reads(single_reduced_tempfile1_sorted, single_reduced_tempfile1,debug)
  File "/home2/nrius/miniconda3/bin/SQuIRE/squire/Count.py", line 378, in reduce_reads
    prev.line_split[15]  = prev_TE_ID
UnboundLocalError: local variable 'prev_TE_ID' referenced before assignment
```
Thanks,

Nuria

**Comment by protatoes** [comment]
Hi, 
I have encountered the same problem.  Is there a known fix for this?

Error output:
Creating temporary files2020-09-29 11:15:22.196229

Creating unique and multiple alignment bedfiles 2020-09-29 11:15:22.266808

Identifying properly paired reads 2020-09-29 11:15:22.266838

Intersecting bam files with TE bedfile 2020-09-29 11:15:22.378292

Splitting into read1 and read 2 2020-09-29 11:15:47.215404

Combining adjacent TEs with same read alignment 2020-09-29 11:15:47.370781

Traceback (most recent call last):
  File "/data4/users/tao.yang/src/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/data4/users/tao.yang/src/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/data4/users/tao.yang/src/SQuIRE/squire/Count.py", line 1683, in main
    reduce_reads(paired_bed_tempfile1_sorted, paired_reduced_tempfile1,debug)
  File "/data4/users/tao.yang/src/SQuIRE/squire/Count.py", line 378, in reduce_reads
    prev.line_split[15]  = prev_TE_ID
UnboundLocalError: local variable 'prev_TE_ID' referenced before assignment

**Comment by fansalon** [comment]
In case you are still troubling with the error, in my understanding this error occurs when the 'paired_bed_tempfile1_sorted' and 'paired_reduced_tempfile1' arguments of the function reduce_reads point to empty files. To understand this I inserted ```print(paired_bed_tempfile1_sorted)``` in line 1684 in /path/to/SQuIRE/squire/Count.py. This outputs in your squire count output (e.g. the slurm/PBS o file) the path to the file that reduce_reads tries to read-in. Just do ```cat /path/to/file``` and see what is contained in the file. This might be of help.

In my situation, I forgot to modify the arguments.sh file and I was therefore trying to align/count mm10 reads to dm6 reference genome.....

Best,
Federico

**Comment by IqRaZaFaR16** [comment]
Hi,
i have encountred I have encountered the same problem. but this command works for pair-end data and shows this error for single-end data. before half of my jobs are done and now its shows an error. Is there a known fix for this?                     
 squire Count -m /home/data/TE-data/Dmrt1-data/Mapping -c /home/data/TE-data/Dmrt1-data/squire_clean -o /home/data/TE-data/Dmrt1-data/counts -t /home/data/TE-data/reference -f /home/data/TE-data/reference -r 50 -n SRR1757699 -b GRCm38 -p 32
Traceback (most recent call last):
  File "/home/iqra/miniconda3/envs/squire_env/bin/squire", line 10, in <module>
    sys.exit(main())
  File "/home/iqra/miniconda3/envs/squire_env/lib/python2.7/site-packages/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home/iqra/miniconda3/envs/squire_env/lib/python2.7/site-packages/squire/Count.py", line 1683, in main
    reduce_reads(paired_bed_tempfile1_sorted, paired_reduced_tempfile1,debug)
  File "/home/iqra/miniconda3/envs/squire_env/lib/python2.7/site-packages/squire/Count.py", line 378, in reduce_reads
    prev.line_split[15]  = prev_TE_ID
UnboundLocalError: local variable 'prev_TE_ID' referenced before assignment
