### ISSUE TITLE
mapping step error 

### ISSUE THREAD

**Issue by mb3188** [wyang17/SQuIRE#29]
Hello, 
I managed to arrive to mapping step, however it stops because of an error (please see below). Any help would be appreciated. 

squire Map --read1  /data/MB998/HepC_Uwe/Uwe_Influenca/FASTqs/A549_DMSO_12h_dNS1_3_20141211_NoIndex_L001_R1_001.fastq.gz  --read2 FALSE --read_length 100 --fetch_folder /data/MB998/SOFTWARE/SQuIRE/fetch_folder --build hg38 --verbosity 
start time is:2019-04-08 18:52:14.682391

Map.pyc

Script Arguments
=================
fetch_folder=/data/MB998/SOFTWARE/SQuIRE/fetch_folder
name=False
extra=None
read_length=100
verbosity=True
pthreads=1
read1=/data/MB998/HepC_Uwe/Uwe_Influenca/FASTqs/A549_DMSO_12h_dNS1_3_20141211_NoIndex_L001_R1_001.fastq.gz
read2=FALSE
build=hg38
func=<function main at 0x7f6a967c5578>
trim3=0
map_folder=squire_map

Traceback (most recent call last):
  File "/home/mb998/miniconda/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/data/MB998/SOFTWARE/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/data/MB998/SOFTWARE/SQuIRE/squire/Map.py", line 301, in main
    index = find_file(fetch_folder,"_STAR",build, 1,True)
  File "/data/MB998/SOFTWARE/SQuIRE/squire/Map.py", line 95, in find_file
    raise Exception("No " + pattern + " file")
Exception: No _STAR file

**Comment by cpacyna** [comment]
Hi Martina,

Sorry for the long response time!  Are you able to find the hg38_STAR directory within your fetch folder?  Did you have any errors in running fetch?  

Regards,
Chloe

**Comment by mb3188** [comment]
Yes I have hg38_STAR in my fetch folder and running fetch does not seem to be producing any error< I have re-run it. 

here is the output of fetch run: 
Apr 12 14:26:54 ..... started STAR run
Apr 12 14:26:54 ... starting to generate Genome files
Apr 12 14:28:41 ... starting to sort Suffix Array. This may take a long time...
Apr 12 14:29:20 ... sorting Suffix Array chunks and saving them to disk...
Apr 12 22:24:32 ... loading chunks from disk, packing SA...
Apr 12 22:26:52 ... finished generating suffix array
Apr 12 22:26:52 ... generating Suffix Array index
Apr 12 22:32:48 ... completed Suffix Array index
Apr 12 22:32:48 ... writing Genome to disk ...
Apr 12 22:32:53 ... writing Suffix Array to disk ...
Apr 12 22:33:37 ... writing SAindex to disk
Apr 12 22:33:44 ..... finished successfully
end time is: 2019-04-12 22:33:45.995932

it took: 8:09:16.714832


Ran again clean and then mapping and got an error complaining about gtf file. Is gtf downoaded or made in fetch step? 

Error log: 

(squire) [mb998@cbsumezey01 SQuIRE]$ squire Map --read1 /data/MB998/HepC_Uwe/Uwe_Influenca/FASTqs/A549_DMSO_12h_dNS1_3_20141211_NoIndex_L001_R1_001.fastq.gz --read2 FALSE --read_length 1\
> 00 --fetch_folder /data/MB998/SOFTWARE/SQuIRE/hg38_ref --build hg38 --verbosity >> Map.out &
[1] 62111
(squire) [mb998@cbsumezey01 SQuIRE]$ start time is:2019-04-12 23:09:30.242620

Map.pyc


fetch_folder=/data/MB998/SOFTWARE/SQuIRE/hg38_ref
name=False
extra=None
read_length=100
verbosity=True
pthreads=1
read1=/data/MB998/HepC_Uwe/Uwe_Influenca/FASTqs/A549_DMSO_12h_dNS1_3_20141211_NoIndex_L001_R1_001.fastq.gz
read2=FALSE
build=hg38
func=<function main at 0x7f0fd4235578>
trim3=0
map_folder=squire_map


Traceback (most recent call last):
  File "/home/mb998/miniconda/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/data/MB998/SOFTWARE/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/data/MB998/SOFTWARE/SQuIRE/squire/Map.py", line 303, in main
    gtf = find_file(fetch_folder,"_refGene.gtf",build, 1,True)
  File "/data/MB998/SOFTWARE/SQuIRE/squire/Map.py", line 95, in find_file
    raise Exception("No " + pattern + " file")
Exception: No _refGene.gtf file

**Comment by netwchao** [comment]
> Hello,
> I managed to arrive to mapping step, however it stops because of an error (please see below). Any help would be appreciated.
> Thanks,
> Martina
> 
> squire Map --read1 /data/MB998/HepC_Uwe/Uwe_Influenca/FASTqs/A549_DMSO_12h_dNS1_3_20141211_NoIndex_L001_R1_001.fastq.gz --read2 FALSE --read_length 100 --fetch_folder /data/MB998/SOFTWARE/SQuIRE/fetch_folder --build hg38 --verbosity
> start time is:2019-04-08 18:52:14.682391
> 
> Map.pyc
> 
> # Script Arguments
> fetch_folder=/data/MB998/SOFTWARE/SQuIRE/fetch_folder
> name=False
> extra=None
> read_length=100
> verbosity=True
> pthreads=1
> read1=/data/MB998/HepC_Uwe/Uwe_Influenca/FASTqs/A549_DMSO_12h_dNS1_3_20141211_NoIndex_L001_R1_001.fastq.gz
> read2=FALSE
> build=hg38
> func=<function main at 0x7f6a967c5578>
> trim3=0
> map_folder=squire_map
> 
> Traceback (most recent call last):
> File "/home/mb998/miniconda/envs/squire/bin/squire", line 11, in
> load_entry_point('SQuIRE', 'console_scripts', 'squire')()
> File "/data/MB998/SOFTWARE/SQuIRE/squire/cli.py", line 156, in main
> subargs.func(args = subargs)
> File "/data/MB998/SOFTWARE/SQuIRE/squire/Map.py", line 301, in main
> index = find_file(fetch_folder,"_STAR",build, 1,True)
> File "/data/MB998/SOFTWARE/SQuIRE/squire/Map.py", line 95, in find_file
> raise Exception("No " + pattern + " file")
> Exception: No _STAR file

maybe，you forgot to activate you vitual enviroment before mapping
