### ISSUE TITLE
UnboundLocalError: local variable 'paired' referenced before assignment

### ISSUE THREAD

**Issue by alerubio** [wyang17/SQuIRE#31]
I am getting this error in only 8 of 86 samples.
Any idea?

**Comment by MaxwellShih** [comment]
Similar here!
I have fixed the potential 'join' issue and successfully run for most of my samples for the 'squire Count' step. 
Afterward I switched to analyze different dataset, I ran into the trouble that squire Count crashed again. Now my error message is

Traceback (most recent call last):
  File "/home/maxwells/bin/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home/maxwells/bin/SQuIRE/squire/cli.py", line 156, in main

Help needed again, please~

**Comment by marieBvr** [comment]
Hi,
Activating this issue again, I have the same error `UnboundLocalError: local variable prev_TE_ID referenced before assignment`. Have you found a solution?

Thx

**Comment by Jinloong-dream** [comment]
> Hi, Activating this issue again, I have the same error `UnboundLocalError: local variable prev_TE_ID referenced before assignment`. Have you found a solution?
> 
> Thx

Hi
I meet the same problem as yours, did you solve this? 
THX
