### ISSUE TITLE
squire Count ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by hyungjoo-lee** [wyang17/SQuIRE#40]
Hi @wyang17 

I have encountered the following ZeroDivisionError during SQuIRE Count stage. I have more than 20 different RNA-seq samples, and only this one has this issue every time I run this.

Could you please resolve this issue?

```
start time is:2020-07-02 13:33:52.016270

Count.pyc

Script Arguments
=================
count_folder=8_squire/squire_count
EM=auto
clean_folder=/scratch/twlab/hlee/genomes/danRer10/squire/squire_clean
fetch_folder=/scratch/twlab/hlee/genomes/danRer10/squire/squire_fetch
name=Kidney_rep1
tempfolder=False
verbosity=True
pthreads=8
strandedness=2
read_length=61
build=danRer10
func=<function main at 0x2b70404309b0>
map_folder=8_squire/squire_map


Quantifying Gene expression 2020-07-02 13:33:52.253733

Running Guided Stringtie on each bamfile Kidney_rep1 2020-07-02 13:33:52.385027

Warning: gene "adob" (on chr17) has reference transcripts on both strands?
Warning: gene "nr4a2a" (on chr9) has reference transcripts on both strands?
Creating temporary files2020-07-02 13:37:17.839948

Creating unique and multiple alignment bedfiles 2020-07-02 13:37:17.853702

Identifying properly paired reads 2020-07-02 13:37:17.853732

Intersecting bam files with TE bedfile 2020-07-02 13:59:53.159556

Splitting into read1 and read 2 2020-07-02 14:06:45.765105

Combining adjacent TEs with same read alignment 2020-07-02 14:07:18.157487

Getting genomic coordinates of read2020-07-02 14:11:31.226259

Identifying and labeling unique and multi reads2020-07-02 14:13:49.211829

Matching paired-end mates and merging coordinates2020-07-02 14:15:44.396913

Adding properly paired reads that have mates outside of TE into matched file2020-07-02 14:27:09.296185

Removing single-end reads that have matching paired-end mates at other alignment locations2020-07-02 14:27:26.819686

Identifying and labeling unique and multi fragments2020-07-02 14:27:43.282618

Identifying multi read pairs with one end unique2020-07-02 14:28:51.554478

counting unique alignments 2020-07-02 14:29:19.007752

counting multi alignments 2020-07-02 14:30:50.949737

Adding Tag information to aligned TEs 2020-07-02 14:31:48.145425

Calculating multialignment assignments 2020-07-02 14:31:49.172457

Running expectation-maximization calculation for iteration:1 2020-07-02 14:31:58.770414

Average change in TE count:0.0 2020-07-02 14:32:00.995930

Max change in TE count:0 2020-07-02 14:32:00.995979

Number changed TE:0 2020-07-02 14:32:00.995991

Number TEs changed by at least 1 count:0 2020-07-02 14:32:00.995997

Number TEs changed by at least 1 count with at least 10 counts:0 2020-07-02 14:32:00.996004

Number TEs changed by at least 1 count with at least 10 counts and > 1pct total count:0 2020-07-02 14:32:00.996010

Expectation maximization changed the average likelihood by: 0.113478553779 2020-07-02 14:32:10.475061

Number of reads with average TE likelihoods changed by at least 0.1: 151086 2020-07-02 14:32:10.475121

Running expectation-maximization calculation for iteration:2 2020-07-02 14:32:10.475132

Traceback (most recent call last):
  File "/home/hyungjoo.lee/bin/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home/hyungjoo.lee/bin/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home/hyungjoo.lee/bin/SQuIRE/squire/Count.py", line 1844, in main
    TE_changecount = RepClass.calcmultiRep(iteration)
  File "/home/hyungjoo.lee/bin/SQuIRE/squire/Count.py", line 948, in calcmultiRep
    self.oldmulti_plus_perkb = self.old_counts_plus/((self.length_plus - avg_fraglength +1)/1000)
ZeroDivisionError: float division by zero

```

**Comment by RoSchwarz** [comment]
Hi,

I have the same issue. Did you find a way to manage this error?

Best,
Robert

**Comment by imtiyazhariyani** [comment]
Hi, I have the same problem for just two of my 24 samples. Anyone manage to figure this out?

**Comment by CWYuan08** [comment]
Hi @hyungjoo-lee, @imtiyazhariyani, @wwliao  I have also encountered the same issue, has anyone fixed it so far? Thank you very much!
