### ISSUE TITLE
Erros in mapping and calling

### ISSUE THREAD

**Issue by mahoko** [wyang17/SQuIRE#45]
Hi, I got the following errors when running squire Map and Call.
It looks like similar problems to #19 , but I am not sure how to fix it. Please would you let me know how to solve these problems?

- Map error.
Traceback (most recent call last):
  File "/data02/home/usr/.pyenv/versions/miniconda3-latest/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/data02/home/usr/bio/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/data02/home/usr/bio/SQuIRE/squire/Map.py", line 387, in main
    align_paired(read1,read2,pthreads,trim3,index,outfile,gtf,gzip,prefix, read_length,extra_fapath)
  File "/data02/home/usr/bio/SQuIRE/squire/Map.py", line 138, in align_paired
    sp.check_call(["/bin/sh", "-c", sortcommand])
  File "/data02/home/usr/.pyenv/versions/miniconda3-latest/envs/squire/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'samtools sort -@ 1 squire_map/01A_R1_trim.fastqAligned.out.bam squire_map/01A_R1_trim.fastq']' returned non-zero exit status 1

I got the above error, but I confirmed I could get bam file by squire map.  So I tried squire call and got the following error. 

- Call error
Traceback (most recent call last):
  File "/data02/home/usr/.pyenv/versions/miniconda3-latest/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/data02/home/usr/bio/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/data02/home/usr/bio/SQuIRE/squire/Call.py", line 270, in main
    group1_list=get_groupfiles(group1,gene_files,subF_files,TE_files,subfamily,count_folder)
  File "/data02/home/usr/bio/SQuIRE/squire/Call.py", line 88, in get_groupfiles
    TE_files.append(find_file(count_folder,"_TEcounts.txt",sample,1,True))
  File "/data02/home/usr/bio/SQuIRE/squire/Call.py", line 43, in find_file
    raise Exception("No " + pattern + " file")

**Comment by mahoko** [comment]
My apologies for the delayed response!  I followed the instruction #19, but could not fix the problem…
So I removed squire and re-installed it. Not sure why, but it worked!  Thank you for developing this nice tool!

**Comment by netwchao** [comment]
Hello，I got the following errors when running squire Call. How can I fix this error：
<img width="503" alt="508d59d1d17538f8db8f6693aa65ca3" src="https://user-images.githubusercontent.com/56786669/104689107-e8c7e200-573c-11eb-889e-f159d1f28b86.png">
