### ISSUE TITLE
issue with running fetch

### ISSUE THREAD

**Issue by iichelhadi** [wyang17/SQuIRE#55]
Hi wyang17,
I am having an issue with running the fetch command as shown below.

`Traceback (most recent call last):
  File "/home/svu/phaei/.conda/miniconda/4.9/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/hpctmp/phaei/FACT/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/hpctmp/phaei/FACT/SQuIRE/squire/Fetch.py", line 231, in main
    raise Exception("Was not able to download chromosome file from UCSC" + "\n", file = sys.stderr)
TypeError: exceptions.Exception does not take keyword arguments
`

I am not sure how to resolve this issue.

regards

**Comment by ryanmboileau** [comment]
Hi, I am having the same issue-- any chance you have found a solution @iichelhadi ? 

Thanks for your consideration,
Ryan

**Comment by iichelhadi** [comment]
> Hi, I am having the same issue-- any chance you have found a solution @iichelhadi ?
> 
> Thanks for your consideration,
> Ryan

Hi Ryan, Apologies. I dont have any issues running squire anymore. I am not sure what caused this issue back then. Could you post your code so I can compare to mine and see?

**Comment by AbhijeetRPatil** [comment]
@ryanmboileau One possible error would be when trying to build a STAR index for a genome. In case you are also trying to build a STAR index then make sure you have set all the parameters that are required to build the index. Forex, squire Fetch -b hg38 -f -r -g -c -x -p 8

**Comment by YayanFeng** [comment]
Hi, I am already set all those parameters when I build the index. However, I am still having the same issues. Do you have found a solution ?
