### ISSUE TITLE
Error in Call step

### ISSUE THREAD

**Issue by AbhijeetRPatil** [wyang17/SQuIRE#61]
I am getting errors while running the call step in SquIRE. The counts were generated successfully without any errors. However, in the call step, I am getting errors. I have attached the errors below:

The following object is masked from ‘package:base:

    apply

Warning message:
multiple methods tables found for ‘pos’ 
[1] "/home/arpatil/dete/TEs_T1D_Normal_Squire_gene_TE_counttable.txt"
[2] "/home/arpatil/dete/TEs_T1D_Normal_Squire_coldata.txt"           
[3] "/home/arpatil/dete"                                             
[4] "TEs_T1D_Normal_Squire"                                          
[5] "4"                                                              
[6] "T1D"                                                            
[7] "Normal"                                                         
[8] "20"                                                             
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  duplicate 'row.names' are not allowed
Calls: as.matrix -> read.delim -> read.table
Execution halted
Traceback (most recent call last):
  File "/home/arpatil/miniconda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home/arpatil/Tools/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home/arpatil/Tools/SQuIRE/squire/Call.py", line 337, in main
    create_rscript(counttable,coldata,outfolder,output_format,projectname,verbosity,str(pthreads),prefilter,condition1,condition2,label_no)
  File "/home/arpatil/Tools/SQuIRE/squire/Call.py", line 198, in create_rscript
    sp.check_call(["/bin/sh","-c",Rcommand])
  File "/home/arpatil/miniconda3/envs/squire/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'Rscript /home/arpatil/dete/TEs_T1D_Normal_Squire_R_script.tmpOGNGUJ /home/arpatil/dete/TEs_T1D_Normal_Squire_gene_TE_counttable.txt /home/arpatil/dete/TEs_T1D_Normal_Squire_coldata.txt /home/arpatil/dete TEs_T1D_Normal_Squire 4 T1D Normal 20']' returned non-zero exit status 1

I have the count's table generated. For ex, I got the following files: TEs_T1D_Normal_Squire_coldata.txt, TEs_T1D_Normal_Squire _counttable.txt, TEs_T1D_Normal_Squire _combo.txt files generated successfully. But, it is not giving the differentially expressed TEs output.

Could anyone please help me in addressing this error? Thanks!

**Comment by acruicks-tide** [comment]
I am getting the same error, how did you go about a fix?

**Comment by AbhijeetRPatil** [comment]
> I am getting the same error, how did you go about a fix?

Sorry, I don't remember how I fixed. May be other relevant suggestions in the issues tab would be helpful.
https://github.com/wyang17/SQuIRE/issues/60
