### ISSUE TITLE
How to run "squire Call"

### ISSUE THREAD

**Issue by mars188** [wyang17/SQuIRE#65]
Hello, 

This may be a trivial one but I can't get the squire Call run with two groups of samples. Here is how my code looks like: 

`squire Call --group1 data_analysis/squire_count/Liv1_Hi272_Mut_* -2 data_analysis/squire_count/Liv2_Hi272_Cont_* -A mutant -B control -o data_analysis/squire_call/ -p 24 -v`

The "squire_count" folder contains all the count file:

Then I get the following error:

`Traceback (most recent call last):
  File "/scratch/gencore/conda3/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/scratch/gencore/ma5877/TE/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/scratch/gencore/ma5877/TE/SQuIRE/squire/Call.py", line 270, in main
    group1_list=get_groupfiles(group1,gene_files,subF_files,TE_files,subfamily,count_folder)
  File "/scratch/gencore/ma5877/TE/SQuIRE/squire/Call.py", line 88, in get_groupfiles
    TE_files.append(find_file(count_folder,"_TEcounts.txt",sample,1,True))
  File "/scratch/gencore/ma5877/TE/SQuIRE/squire/Call.py", line 43, in find_file
    raise Exception("No " + pattern + " file")
Exception: No _TEcounts.txt file`

But "_TEcounts.txt" file is there in the "squire_count" folder. Am I providing the wrong script? Please help!

**Comment by mars188** [comment]
Ok I have solved the issue. It requires "-i" option for count folder that was not mentioned in the manual but if you do `squire Call --help` then it shows all the option including that "-i".
