### ISSUE TITLE
Errors occured in SQuIRE Count step

### ISSUE THREAD

**Issue by YayanFeng55** [wyang17/SQuIRE#68]
Hi Yang,

I am so glad that you have developed such an amazing software for expression quantfication of transposable elements. But now it occured a weird error in Count step, the script I used worked well for other samples, but it reports error as follows now:

Warning: gene "TTTY3B" (on chrY) has reference transcripts on both strands?
Traceback (most recent call last) :
File "/home/fengy2/beegfs/Resources/miniconda3/envs/squire/bin/squire", line 11, in ‹module>
load entry point ('SQuIRE' 'console scripts 'squire') ()
File "/mnt/beegfs/fengy2/Resources/miniconda3/sQuIRE/squire/cli.py",line156,inmain
subargs. func (args subargs)
File "/mnt/beegfs/fengy2/Resources/miniconda3/SQuIRE/squire/Count.py", line 1803, in main
avg fraglength=uniquecount (unique bedfile, RepCalc dict.read locdict)
File "/mnt/beegfs/fengy2/Resources/miniconda3/sQuIRE/squire/Count.py",line1229,inuniquecount
unique_fragavg-unique fragsum/int (unique linecount)
ZeroDivisionError: division by zero

How can I solve this problem? I have tried to use 80Gb larger memory to run Count. So I don't think it is not memory issues. Could you help me solve this problem? Thank you so much in advance.

Thanks,
Yayan Feng

**Comment by CWYuan08** [comment]
Hi, @YayanFeng55, I have also encountered the same issue, have you fixed it so far? Thank you very much!

**Comment by jakewendt** [comment]
I had 4 out of my 13 samples doing this.

I added ` if unique_linecount > 0 else 0` to the end of line 1229.

```
sed -i 's/unique_fragavg=unique_fragsum\/int(unique_linecount)/unique_fragavg=unique_fragsum\/int\(unique_linecount\) if unique_linecount \> 0 else 0/' squire/Count.py
```

Worked for me. Well it didn't crash after that.
