### ISSUE TITLE
Sorting Issue With SQuIRE Map 

### ISSUE THREAD

**Issue by Sesukai** [wyang17/SQuIRE#71]
Hello,

I have been having encountering an error running the SQuIRE Map command on my Fastqs.

Traceback (most recent call last):
  File "/gs/gsfs0/users/skattapong/.conda/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/gs/gsfs0/users/skattapong/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/gs/gsfs0/users/skattapong/SQuIRE/squire/Map.py", line 387, in main
    align_paired(read1,read2,pthreads,trim3,index,outfile,gtf,gzip,prefix, read_length,extra_fapath)
  File "/gs/gsfs0/users/skattapong/SQuIRE/squire/Map.py", line 138, in align_paired
    sp.check_call(["/bin/sh", "-c", sortcommand])
  File "/gs/gsfs0/users/skattapong/.conda/envs/squire/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/bin/sh', '-c', 'samtools sort -@ 48 squire_map/SRR9127453Aligned.out.bam squire_map/SRR9127453']' returned non-zero exit status 1

I see that there is an issue with the samtools sort command here, so I was wondering if there was a way to manually sort the Aligned.out.bam files.

I attached the script I used here:
[Squire_Map.txt](https://github.com/wyang17/SQuIRE/files/8018682/Squire_Map.txt)

Thank you,
Seth

**Comment by jakewendt** [comment]
I just had the same error. It is because the format of the samtools sort command format is from an older version. Either downgrade your samtools to around version 0.1.18 or modify Map.py.

**Comment by jamesc99** [comment]
> 

Hi,

May I ask how I can downgrade the samtools/modify Map.py? Thanks so much!

Sincerely,
Ryan

**Comment by jakewendt** [comment]
Either install an older version of samtools. 0.1.18 would work.

Or edit `squire/Map.py` around line 136 and change the sort command

```
# samtools version 0.1.18 sort format
sortcommand_list = ["samtools", "sort", "-@",str(pthreads), STAR_output, prefix]
```

```
# samtools version 1.9 sort format
sortcommand_list = ["samtools", "sort", "-@",str(pthreads), "-o",outfile, STAR_output]
```
