### ISSUE TITLE
error with " TypeError: sequence item 2: expected string, bool found"

### ISSUE THREAD

**Issue by jianguozhouzunyimedicaluniversity** [wyang17/SQuIRE#76]
Dear @wyang17 I run the first two steps, map, and count, but draw I have the error.
````
(squire) [zhou@localhost squire]$     squire Draw --map_folder ${dir}/squire --draw_folder ${dir}/squire --name ${i} --build ${ref} --pthreads 30
````

````
May 08 13:34:27 ..... reading from BAM, output wiggle
May 08 13:37:10 ..... done
Traceback (most recent call last):
  File "/home/zhou/miniconda2/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home/zhou/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home/zhou/SQuIRE/squire/Draw.py", line 188, in main
    make_bigwig(chrominfo,bedgraph_list)
  File "/home/zhou/SQuIRE/squire/Draw.py", line 131, in make_bigwig
    igvcommand=" ".join(igvcommand_list)
TypeError: sequence item 2: expected string, bool found
````

**Comment by nkurtys** [comment]
I have the same issue and I cannot figure out how to fix it.

**Comment by wenyuhaokikika** [comment]
I encountered the same issue, which occurred because there was a boolean value when concatenating the `bedGraphToBigWig` command, and I printed it out.
```
igvcommand_list ['bedGraphToBigWig', '/workplace/example/result/squire_draw/SRR4016861.bam_plus_unique.bedgraph', False, '/workplace/example/result/squire_draw/SRR4016861.bam_plus_unique.bedgraph.bw']
Traceback (most recent call last):
  File "/usr/local/envs/squire/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/SQuIRE/squire/Draw.py", line 189, in main
    print("Making unique and total bigwigs "+ str(datetime.now())  + "\n",file = sys.stderr)    
  File "/SQuIRE/squire/Draw.py", line 132, in make_bigwig
    print('igvcommand_list',igvcommand_list)
TypeError: sequence item 2: expected string, bool found
```
When I ran

```
[root@14116a6d147f example]# bedGraphToBigWig   
bedGraphToBigWig v 4 - Convert a bedGraph file to bigWig format.
usage:
   bedGraphToBigWig in.bedGraph chrom.sizes out.bw
where in.bedGraph is a four column file in the format:
      <chrom> <start> <end> <value>
and chrom.sizes is a two-column file/URL: <chromosome name> <size in bases>
and out.bw is the output indexed big wig file.
If the assembly <db> is hosted by UCSC, chrom.sizes can be a URL like
  http://hgdownload.cse.ucsc.edu/goldenPath/<db>/bigZips/<db>.chrom.sizes
or you may use the script fetchChromSizes to download the chrom.sizes file.
If not hosted by UCSC, a chrom.sizes file can be generated by running
twoBitInfo on the assembly .2bit file.
The input bedGraph file must be sorted, use the unix sort command:
  sort -k1,1 -k2,2n unsorted.bedGraph > sorted.bedGraph
options:
   -blockSize=N - Number of items to bundle in r-tree.  Default 256
   -itemsPerSlot=N - Number of data points bundled at lowest level. Default 1024
   -unc - If set, do not use compression.

```
It can be seen that `bedGraphToBigWig` requires three parameters: `in.bedGraph`, `chrom.sizes`, and `out.bw`. The first and third parameters are available now, but the second parameter `chrom.sizes` is `false`, which is the variable `chrominfo` in the code.
`185     chrominfo = find_file(fetch_folder,"_chromInfo.txt",build,1)`
If the file is not found, `find_file` will output `False`.

**So the main reason is that `fetch_folder` is incorrect. Please ensure that `call` is run in the `script` directory, and `draw` must be run in the same directory level as `squire_fetch`, otherwise a file exception error will be thrown!!! It is hoped that the author will fix these issues later to enable the environment to run properly with absolute paths.**


Finally, I have listed the execution order, file structure, and the paths of the execution commands below, which I hope will be of some reference.

run.sh
```sh
#!/bin/sh
echo "running...fetch"
sh ./scripts/fetch.sh ./scripts/arguments.sh > ./logs/fetch.log 2>&1
echo "running...clean"
sh ./scripts/clean.sh ./scripts/arguments.sh > ./logs/clean.log 2>&1
echo "running...loop_map"
sh ./scripts/loop_map.sh ./scripts/arguments.sh > ./logs/loop_map.log 2>&1
echo "running...loop_count"
sh ./scripts/loop_count.sh ./scripts/arguments.sh > ./logs/loop_count.log 2>&1
echo "running...call"
cd scripts && sh ../scripts/call.sh ../scripts/arguments.sh > ../logs/call.log 2>&1
echo "running...loop_draw"
cd result && sh ../scripts/loop_draw.sh ../scripts/arguments.sh  > ../logs/loop_draw.log 2>&1
```
worplace
```sh
~/SQuIRE/workplace/example$ tree -L 2 .
.
├── download_path
│   ├── SRR4016860
│   ├── SRR4016861
│   ├── SRR4016864
│   └── SRR4016865
├── download_sra
├── downloadSra.sh
├── fastq
│   ├── SRR4016860_1.fastq.gz
│   ├── SRR4016860_2.fastq.gz
│   ├── SRR4016861_1.fastq.gz
│   ├── SRR4016861_2.fastq.gz
│   ├── SRR4016864_1.fastq.gz
│   ├── SRR4016864_2.fastq.gz
│   ├── SRR4016865_1.fastq.gz
│   └── SRR4016865_2.fastq.gz
├── fastq-dump.log
├── logs
│   ├── call.log
│   ├── clean.log
│   ├── downloadSra.log
│   ├── loop_count.log
│   ├── loop_draw.log
│   └── loop_map.log
├── nohup.out
├── result
│   ├── downloads
│   ├── squire_call_repo
│   ├── squire_clean
│   ├── squire_count
│   ├── squire_draw
│   ├── squire_fetch
│   ├── squire_map
│   └── squire_seek
├── run.sh
├── scripts
│   ├── arguments.sh
│   ├── arguments.sh.bak
│   ├── call.sh
│   ├── clean.sh
│   ├── count.sh
│   ├── draw.sh
│   ├── fail_map_PRJNA870508.txt
│   ├── fetch.sh
│   ├── INSTRUCTIONS
│   ├── loop_count.sh
│   ├── loop_draw.sh
│   ├── loop_map.sh
│   ├── map.sh
│   └── sample_arguments.sh
├── srr_list
└── success_map_drosrepo.txt

18 directories, 34 files
```
