### ISSUE TITLE
Error while running call

### ISSUE THREAD

**Issue by jayramr** [wyang17/SQuIRE#86]
Hi, 

Please help with sorting this issue 

I already reinstalled the squire package still same error

```
squire Call -1 LDN-M* -2 LDN-S* -A mutant -B sibs -i data/analysis/squire_count/ -o data/analysis/squire_call/locus -p 24 -v
Script start time is:2022-12-14 13:35:55.982279

Script Arguments
=================
count_folder=data/analysis/squire_count/
projectname=SQuIRE
output_format=html
pthreads=24
call_folder=data/analysis/squire_call/locus
condition2=sibs
table_only=False
group1=LDN-M1_ACAGTG_L003_R1_001.fastq.gz
func=<function main at 0x1555534c46e0>
group2=LDN-S1_CTTGTA_L003_R1_001.fastq.gz
subfamily=False
verbosity=True
condition1=mutant


Traceback (most recent call last):
  File "/scratch/gencore/conda3/envs/squire/bin/squire", line 10, in <module>
    sys.exit(main())
  File "/scratch/gencore/conda3/envs/squire/lib/python2.7/site-packages/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/scratch/gencore/conda3/envs/squire/lib/python2.7/site-packages/squire/Call.py", line 271, in main
    group1_list=get_groupfiles(group1,gene_files,subF_files,TE_files,subfamily,count_folder)
  File "/scratch/gencore/conda3/envs/squire/lib/python2.7/site-packages/squire/Call.py", line 88, in get_groupfiles
    TE_files.append(find_file(count_folder,"_TEcounts.txt",sample,1,True))
  File "/scratch/gencore/conda3/envs/squire/lib/python2.7/site-packages/squire/Call.py", line 43, in find_file
    raise Exception("No " + pattern + " file")
Exception: No _TEcounts.txt file
```

And the files are available in the below location 
```
ls -l data/analysis/squire_count/*_TEcounts.txt
```

Thanks
Jay

**Comment by mengying0714** [comment]
I have the same question, Have you solved it?

**Comment by jayramr** [comment]
No i never tried after that.

**Comment by acruicks-tide** [comment]
It looks like you are inputting fastq files into the Call function. You need to run Fetch, Clean, Map and Count before you can run Call. The *_TEcounts.txt files are output from the Count subroutine.

**Comment by microsfeno** [comment]
I also have the same problem:

Traceback (most recent call last):
  File "/home/user/miniforge3/envs/squire27/bin/squire", line 11, in <module>
    load_entry_point('SQuIRE', 'console_scripts', 'squire')()
  File "/home/user/SQuIRE/squire/cli.py", line 156, in main
    subargs.func(args = subargs)
  File "/home/user/SQuIRE/squire/Call.py", line 270, in main
    group1_list=get_groupfiles(group1,gene_files,subF_files,TE_files,subfamily,count_folder)
  File "/home/user/SQuIRE/squire/Call.py", line 88, in get_groupfiles
    TE_files.append(find_file(count_folder,"_TEcounts.txt",sample,1,True))
  File "/home/user/SQuIRE/squire/Call.py", line 43, in find_file
    raise Exception("No " + pattern + " file")
Exception: No _TEcounts.txt file
