### ISSUE TITLE
Unable to Install SQuIRE

### ISSUE THREAD

**Issue by frentzeperis** [wyang17/SQuIRE#98]
Hello,

I am trying to set up SQuIRE on my school's hpc cluster but the installation is failing (at: mamba create -n squire -c bioconda squire). I have a new account and have tried conda and mamba create on fresh installations of miniconda 2, miniconda 3, and the most recent anaconda. All of them are failing to create the squire environment with an error that reads some variant of:

Collecting package metadata (current_repodata.json): done
Solving environment: unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \ 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: 

And then I am returned to the command line. Mamba gives bit more detail about which packages conflict but the whole thing is so strange. My local installation of SQuIRE on my MacBook worked fine but this is failing. Do you have any insights?

Best,
Frederika

**Comment by MatteoT23** [comment]
Hi,

I'm also encountering problems when attempting to install SQuIRE. So far, I tried the following alternatives:

1. `mamba create -n squire -c bioconda squire`; which returns variations of the following:
**Encountered problems while solving.
Problem: package squire-0.9.9.92-pyhdfd78af_0 requires samtools 1.1, but none of the providers can be installed**


2. `conda create --name squire.env --override-channels -c iuc -c bioconda -c conda-forge -c defaults -c r python=2.7.13 bioconductor-deseq2=1.16.1 r-base=3.4.1 r-pheatmap bioconductor-vsn bioconductor-biocparallel=1.12.0 r-ggrepel  star=2.5.3a  bedtools=2.25.0 samtools=1.1 stringtie=1.3.3 igvtools=2.3.93  ucsc-genepredtobed  ucsc-gtftogenepred  ucsc-genepredtogtf  ucsc-bedgraphtobigwig r-hexbin` ; which returns:
**UnsatisfiableError: The following specifications were found to be incompatible with each other:
Output in format: Requested package -> Available versions
Package PACKAGE_NAME conflicts for:
(...long list of conflicts...)**

Any help would be great! :)
Thank you

Best,
Matteo

**Comment by singhbhavya** [comment]
Updating this issue with what worked for me:

I built an empty environment, in which I installed the specified R version.
```
conda create -n squire
conda activate squire
conda install r-base=3.4.1

```

I then downloaded SQuIRE from Git, and installed it manually.

```
git clone https://github.com/wyang17/SQuIRE; cd SQuIRE; pip install -e .
```

I ran SQuIRE Build

```
squire Build -s all
```

I downloaded a few more dependencies based on what was required / as errors popped up:

```
conda install -c bioconda ucsc-gtftogenepred
conda install -c bioconda ucsc-genepredtogtf
conda install -c bioconda ucsc-bedgraphtobigwig
conda install -c bioconda ucsc-genepredtobed
```

I ran SQuIRE Fetch, using these commands:

```
squire Fetch -b hg38 -f -c -r -g -x -p 8 -v
```

SQuIRE Clean:

```
squire Clean -b hg38
```

SQuIRE Map 

```
squire Map -1 [read1.fastq] -2  [read2.fastq] -o [outputfolder] --name [name] -b hg38 --verbosity
```

SquIRE Count

```
squire Count -m [mapping_folder]  -o [outputfolder]  -t [tmp] -r 60 -n IFF1 -b hg38 --verbosity
```

I exported my current conda env (if it's helpful for anyone), and this is what it looks like:

```
conda env export --from-history 
```

```
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base=3.4.1
  - ucsc-genepredtogtf
  - ucsc-genepredtobed
  - ca-certificates
  - certifi
  - openssl
  - ucsc-gtftogenepred
  - ucsc-bedgraphtobigwig
```

**Comment by Kiliankleemann** [comment]
thanks for the comment @singhbhavya - tried it our but i got the following: Traceback (most recent call last):
  File "/home/kilian/miniconda3/bin/squire", line 33, in <module>
    sys.exit(load_entry_point('SQuIRE', 'console_scripts', 'squire')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kilian/miniconda3/bin/squire", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/kilian/miniconda3/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kilian/miniconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/kilian/SQuIRE/squire/cli.py", line 17, in <module>
    import Build as s1
  File "/home/kilian/SQuIRE/squire/Build.py", line 28
    os.makedirs(path, 0770)
                      ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers

**Comment by J-Wengler** [comment]
Any update to this? I attemped to follow @singhbhavya's method and received the same error as @Kiliankleemann.

**Comment by singhbhavya** [comment]
I know this is late, but for everyone else having problems with `squire Build` (@J-Wengler, @Kiliankleemann), a solution is to manually download and build the four programs (samtools, bedtools, stringtie, star) and store them in the Squire directory in the same format as the program would in the `Squire build` command. I had to re-create my Squire environment and also came across similar issues with `squire Build`, and this is what I did. :) 

Then you can basically ignore the Build step, and proceed onwards with the steps. As long as the programs above are in your path and callable, there shouldn't be an issue.
